[build]
  publish = "static"
  command = "source venv/bin/activate && pip install -r requirements.txt && python app.py"

[context.production.environment]
  NETLIFY_AUTH_TOKEN = "${NETLIFY_AUTH_TOKEN}"

[build.environment]
  PYTHON_VERSION = "3.8"

[functions]
  directory = "netlify/functions"

[settings]
  python = "3.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200