name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: greenbreard/imageconversion:tagname

      - name: Post Log in to Docker Hub
        run: echo "Logged in to Docker Hub"

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Post Set up Docker Buildx
        run: echo "Set up Docker Buildx"

      - name: Build and push Docker image
        run: docker buildx build --push --tag greenbreard/imageconversion:tagname .
