name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        echo "Virtual environment created. Listing contents of venv/bin:"
        ls -l venv/bin/
        source venv/bin/activate
        echo "Virtual environment activated. Installing dependencies:"
        pip install -r requirements.txt
        echo "Dependencies installed. Listing contents of venv/bin again:"
        ls -l venv/bin/
      shell: bash

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -fsSL https://cli-assets.render.com/install.sh | sh
        render deploy --service srv-cqae88tds78s739qgpjg --token ${{ secrets.RENDER_API_KEY }}
